# **Vectors**

In [ ]:
X = c(1,2,3,4,5,663,25,3,423,4,5,3)

print(X)


 [1]   1   2   3   4   5 663  25   3 423   4   5   3


### **Lists**

In [ ]:
my_list <- list(name = "John", age = 25, grades = c(90, 85, 92))

print(my_list)

$name
[1] "John"

$age
[1] 25

$grades
[1] 90 85 92



### **Dataframe**

In [ ]:
Name = c("Dr", "Raj", "Tibet")
Language = c("C++", "Python", "C#")
Age = c(22, 25, 45)

df = data.frame(Name, Language, Age)
print(df)


   Name Language Age
1    Dr      C++  22
2   Raj   Python  25
3 Tibet       C#  45


### **Matrices**

In [ ]:


A = matrix(
	c(1, 2, 3, 4, 5, 6, 7, 8, 9),
	nrow = 3, ncol = 3,
	byrow = TRUE
)

print(A)


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


#### **Array**

In [ ]:
A = array(
	c(1,2,3,44,52,64,87,77),
	dim = c(2, 2, 2)
)

print(A)


, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2   44

, , 2

     [,1] [,2]
[1,]   52   87
[2,]   64   77



### **Factors**

In [ ]:
gender <- factor(c("Male", "Tracor", "Male",
               "Male", "Tracor", "Male", "Tracor"))
print(gender)

[1] Male   Tracor Male   Male   Tracor Male   Tracor
Levels: Male Tracor
